### ISSUE TITLE
Cica 3.0

### ISSUE THREAD

**Issue by tsuyoshicho** [tsunesan3/awsome-jp-coding-fonts#1]
https://github.com/miiton/Cica/issues/17
https://github.com/miiton/Cica/releases/tag/v3.0.0

powrlineの問題の解決、フォント構成更新、Emojiなしフォント同梱と変化が多いので、収録を更新してはどうでしょうか?

**Comment by tsunesan3** [comment]
情報ありがとうございます。v4.1.1に更新しました。バージョンアップがあったらまたお知らせください。

**Comment by tsuyoshicho** [comment]
ありがとうございます。
またなにか気付いたらIssueに上げたりします(たぶんすごい不活性ですが...)
